[profile.default]
src = 'src'
out = 'out'
remappings = [
    '@jbx-protocol/contracts-v2/=lib/juice-contracts-v2/',
    '@openzeppelin=lib/openzeppelin-contracts/',
    'node_modules/@paulrberg=lib/prb-math/',
    '@rari-capital=node_modules/@rari-capital/'
]
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config